name: Check Format
on:
  push:
  pull_request:
      branches:
        - master
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.x'
          cache: npm

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier
        run: prettier --write "./**/*.{js,css,json,scss}"

      - name: Check Format
        run: |
          prettier -c "./**/*.{js,css,json}"
